### ISSUE TITLE
Risk of collisions for 'oscar' as the name of the modules

### ISSUE THREAD

**Issue by jnak** [oscarhealth/oscar.flag#3]
It seems that having the base module called oscar could very easily collide with other modules in the future. Also I rarely see python packages with a dot in the their name. 

What are your thoughts about a one word name with low risk of collisions like oflag ?

**Comment by ianschenck** [comment]
`oscar` is a namespace package, meaning other modules can be installed from different distribution packages, separately. We made the decision that a namespace for modules that would otherwise have very common/generic names (e.g. `flag`) would be preferable in these cases to renaming the package itself.

**Comment by jnak** [comment]
Cool! I didn't know about it.
